language: ruby
rvm:
- 2.1.1
script: jekyll build --destination _site/java && htmlproof ./_site

branches:
  only:
  - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  email: false
