title: Java
baseurl: /java

disqus: zjgsujava

defaults:
  -
    scope:
      path: ''
      type: pages
    values:
      layout: page

exclude: [LICENSE, Gemfile, Gemfile.lock, README.md, vendor]

sass:
    style: compressed
